add_library(smedley_trace_core STATIC trace.cpp)
target_compile_definitions(smedley_trace_core PRIVATE UNICODE _UNICODE WIN32_LEAN_AND_MEAN NOMINMAX)
add_executable(smedley_trace main.cpp)
target_link_libraries(smedley_trace PRIVATE smedley_trace_core)
if(BUILD_TESTING)
  add_executable(smedley_trace_tests trace_test.cpp)
  target_link_libraries(smedley_trace_tests PRIVATE smedley_trace_core GTest::gtest_main)
  include(GoogleTest)
  gtest_discover_tests(smedley_trace_tests DISCOVERY_TIMEOUT 30)
endif()
if(EXISTS ${V2_GAME_DIR})
  install(TARGETS smedley_trace DESTINATION ${V2_GAME_DIR})
endif()
