add_library(smedley_launcher_core STATIC src/launcher.cpp)
target_compile_definitions(smedley_launcher_core PRIVATE UNICODE _UNICODE WIN32_LEAN_AND_MEAN NOMINMAX)
target_include_directories(smedley_launcher_core PUBLIC "../../include" PRIVATE "../../include/toml")
target_link_libraries(smedley_launcher_core PRIVATE bcrypt shell32 ole32)

if(BUILD_TESTING)
    add_executable(smedley_launcher_core_tests tests/launcher_test.cpp)
    target_link_libraries(smedley_launcher_core_tests PRIVATE smedley_launcher_core GTest::gtest_main)
    include(GoogleTest)
    gtest_discover_tests(smedley_launcher_core_tests)
endif()
